# Generated by Django 5.2.11 on 2026-02-13 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], max_length=20)),
                ('template_file', models.FileField(upload_to='templates/')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_number', models.IntegerField(help_text='Display order in financial statements')),
                ('title', models.CharField(help_text='e.g. "Revenue", "Related Party Transactions"', max_length=255)),
                ('template_text', models.TextField(help_text='Note body with merge fields for dynamic data')),
                ('trigger_type', models.CharField(choices=[('always', 'Always (mandatory)'), ('conditional', 'Conditional (account-based)'), ('entity_based', 'Entity-based')], max_length=20)),
                ('trigger_condition', models.JSONField(blank=True, default=dict, help_text='Conditions: account code ranges, entity types, thresholds, etc.')),
                ('applicable_entities', models.JSONField(blank=True, default=list, help_text='Entity types this note can appear for, e.g. ["company", "trust"]')),
                ('aasb_reference', models.CharField(blank=True, help_text='e.g. "AASB 15"', max_length=50)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['note_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('import', 'Data Import'), ('adjustment', 'Adjustment Created'), ('generate', 'Document Generated'), ('status_change', 'Status Changed'), ('mapping_change', 'Mapping Changed'), ('user_change', 'User Modified'), ('template_change', 'Template Modified')], max_length=20)),
                ('description', models.TextField()),
                ('affected_object_type', models.CharField(blank=True, max_length=100)),
                ('affected_object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('xpm_client_id', models.CharField(blank=True, help_text='Xero Practice Manager reference', max_length=100, verbose_name='XPM Client ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], max_length=20)),
                ('abn', models.CharField(blank=True, max_length=11, verbose_name='ABN')),
                ('acn', models.CharField(blank=True, help_text='Companies only', max_length=9, verbose_name='ACN')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('financial_year_end', models.CharField(default='06-30', help_text='Month-day format, e.g. 06-30 for June', max_length=5)),
                ('reporting_framework', models.CharField(choices=[('GPFR_tier1', 'General Purpose (Tier 1)'), ('GPFR_tier2', 'General Purpose (Tier 2)'), ('SPFR', 'Special Purpose')], default='SPFR', max_length=20)),
                ('company_size', models.CharField(blank=True, choices=[('small_proprietary', 'Small Proprietary'), ('large_proprietary', 'Large Proprietary'), ('public', 'Public')], help_text='Companies only', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible storage: directors, trustees, partners, registered address, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.client')),
                ('template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='core.financialstatementtemplate')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['entity_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_label', models.CharField(help_text='e.g. "FY2025"', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('finalised', 'Finalised')], default='draft', max_length=20)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='core.entity')),
                ('prior_year', models.ForeignKey(blank=True, help_text='Link to prior year for comparatives', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_year', to='core.financialyear')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'financial years',
                'ordering': ['-end_date'],
                'unique_together': {('entity', 'year_label')},
            },
        ),
        migrations.CreateModel(
            name='AdjustingJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journals', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjusting_journals', to='core.financialyear')),
            ],
            options={
                'ordering': ['-journal_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='generated/')),
                ('file_format', models.CharField(default='docx', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='core.financialyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.adjustingjournal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_code', models.CharField(help_text='MC&S standard chart code, e.g. "REV001"', max_length=20, unique=True)),
                ('line_item_label', models.CharField(help_text='Display label, e.g. "Revenue from contracts with customers"', max_length=255)),
                ('financial_statement', models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('equity', 'Statement of Changes in Equity'), ('cash_flow', 'Cash Flow Statement')], max_length=20)),
                ('statement_section', models.CharField(help_text='e.g. "Current Assets", "Operating Revenue"', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('applicable_entities', models.JSONField(blank=True, default=list, help_text='Entity types this applies to, e.g. ["company", "trust"]')),
                ('note_trigger', models.ForeignKey(blank=True, help_text='Which disclosure note this line activates when non-zero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_mappings', to='core.notetemplate')),
            ],
            options={
                'ordering': ['financial_statement', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TrialBalanceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_adjustment', models.BooleanField(default=False, help_text='True if this line was created by an adjusting journal entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_lines', to='core.financialyear')),
                ('mapped_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_balance_lines', to='core.accountmapping')),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='ClientAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_account_code', models.CharField(max_length=20)),
                ('client_account_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_mappings', to='core.accountmapping')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='core.entity')),
            ],
            options={
                'ordering': ['client_account_code'],
                'unique_together': {('entity', 'client_account_code')},
            },
        ),
    ]
