# Generated by Django 5.2.11 on 2026-02-15 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityOfficer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('director', 'Director'), ('partner', 'Partner'), ('trustee', 'Trustee'), ('beneficiary', 'Beneficiary'), ('secretary', 'Secretary'), ('public_officer', 'Public Officer'), ('sole_trader', 'Sole Trader / Proprietor')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title, e.g. "Managing Director", "Senior Partner"', max_length=50)),
                ('date_appointed', models.DateField(blank=True, null=True)),
                ('date_ceased', models.DateField(blank=True, null=True)),
                ('is_signatory', models.BooleanField(default=True, help_text='Whether this person signs the financial statements')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which signatories appear on declaration page')),
                ('profit_share_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Partnership profit share % (partnerships only)', max_digits=5, null=True)),
                ('distribution_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Distribution % (trust beneficiaries only)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='core.entity')),
            ],
            options={
                'verbose_name': 'Entity Officer / Signatory',
                'verbose_name_plural': 'Entity Officers / Signatories',
                'ordering': ['entity', 'display_order', 'full_name'],
            },
        ),
    ]
