# Generated by Django 5.2.11 on 2026-02-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entityofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='show_cents',
            field=models.BooleanField(default=False, help_text='Show amounts with cents (2 decimal places). Default for trusts and sole traders.'),
        ),
        migrations.AddField(
            model_name='entity',
            name='trading_as',
            field=models.CharField(blank=True, help_text="Trading name, e.g. 'Southy's Structures'", max_length=255),
        ),
    ]
