# Generated by Django 5.2.11 on 2026-02-16 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entity_show_cents_entity_trading_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Asset category, e.g. "Furniture and Fixtures", "Motor Vehicles"', max_length=100)),
                ('asset_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Original purchase cost', max_digits=15)),
                ('private_use_pct', models.DecimalField(decimal_places=2, default=0, help_text='Private use percentage (0-100)', max_digits=5)),
                ('opening_wdv', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Opening WDV')),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_consideration', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('addition_date', models.DateField(blank=True, null=True)),
                ('addition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depreciable_value', models.DecimalField(decimal_places=2, default=0, help_text='Value on which depreciation is calculated', max_digits=15)),
                ('method', models.CharField(choices=[('D', 'Diminishing Value'), ('P', 'Prime Cost'), ('W', 'Written Off')], default='D', max_length=1)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Depreciation rate as percentage', max_digits=7)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, default=0, help_text='Depreciation charged this year', max_digits=15)),
                ('private_depreciation', models.DecimalField(decimal_places=2, default=0, help_text='Private portion of depreciation', max_digits=15)),
                ('closing_wdv', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Closing WDV')),
                ('profit_on_disposal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loss_on_disposal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_assets', to='core.financialyear')),
            ],
            options={
                'verbose_name': 'Depreciation Asset',
                'verbose_name_plural': 'Depreciation Assets',
                'ordering': ['category', 'display_order', 'asset_name'],
            },
        ),
    ]
