# Generated by Django 5.2.11 on 2026-02-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_depreciationasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalanceline',
            name='prior_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prior year credit amount for comparative column', max_digits=15),
        ),
        migrations.AddField(
            model_name='trialbalanceline',
            name='prior_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prior year debit amount for comparative column', max_digits=15),
        ),
    ]
