# Generated by Django 5.2.11 on 2026-02-16 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trialbalanceline_prior_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalline',
            options={'ordering': ['line_number', 'id']},
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='journal_type',
            field=models.CharField(choices=[('general', 'General Journal'), ('adjusting', 'Adjusting Entry'), ('reversing', 'Reversing Entry'), ('year_end', 'Year-End Entry'), ('depreciation', 'Depreciation Entry'), ('tax', 'Tax Adjustment')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='narration',
            field=models.TextField(blank=True, help_text='Additional notes or explanation for audit purposes'),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Auto-generated sequential reference, e.g. JE-001', max_length=20),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='reversal_of_journal',
            field=models.ForeignKey(blank=True, help_text='The original journal this entry reverses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_journal', to='core.adjustingjournal'),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='The reversing journal that reversed this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='core.adjustingjournal'),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cached total credit for quick display', max_digits=15),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cached total debit for quick display', max_digits=15),
        ),
        migrations.AddField(
            model_name='adjustingjournal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='description',
            field=models.CharField(blank=True, help_text='Optional per-line description', max_length=255),
        ),
        migrations.AddField(
            model_name='journalline',
            name='line_number',
            field=models.IntegerField(default=0, help_text='Display order within the journal'),
        ),
    ]
