# Generated by Django 5.2.11 on 2026-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enhanced_journal_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustingjournal',
            name='reversal_of_journal',
        ),
        migrations.RemoveField(
            model_name='adjustingjournal',
            name='reversed_by',
        ),
        migrations.AlterField(
            model_name='adjustingjournal',
            name='journal_type',
            field=models.CharField(choices=[('general', 'General Journal'), ('adjusting', 'Adjusting Entry'), ('year_end', 'Year-End Entry'), ('depreciation', 'Depreciation Entry'), ('tax', 'Tax Adjustment')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='adjustingjournal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20),
        ),
    ]
