# Generated by Django 5.2.11 on 2026-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_adjustingjournal_reversal_of_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_gst_registered',
            field=models.BooleanField(default=True, help_text='Whether this entity is registered for GST. Affects bank statement coding.'),
        ),
    ]
