# Generated by Django 5.2.11 on 2026-02-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_entity_is_gst_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='period_type',
            field=models.CharField(choices=[('annual', 'Annual (Full Year)'), ('half_year', 'Half-Year'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('interim', 'Interim (Custom Period)')], default='annual', help_text='Type of reporting period', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='year_label',
            field=models.CharField(help_text='e.g. "FY2025" or "Q1 2025"', max_length=20),
        ),
    ]
