# Generated by Django 5.2.11 on 2026-02-17 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_financialyear_period_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('rule_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('variance', 'Variance Analysis'), ('cgt', 'Capital Gains Tax'), ('division_7a', 'Division 7A'), ('expenses', 'Expense Analysis'), ('fbt', 'Fringe Benefits Tax'), ('general', 'General'), ('gst', 'GST'), ('solvency', 'Solvency'), ('superannuation', 'Superannuation'), ('trust', 'Trust'), ('related_party', 'Related Party')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('tier', models.IntegerField(help_text='Processing tier: 1=variance analysis, 2=compliance checks')),
                ('applicable_entities', models.JSONField(default=list, help_text='Entity types this rule applies to, e.g. ["company", "trust"]')),
                ('trigger_config', models.JSONField(default=dict, help_text='Configuration for how this rule evaluates data')),
                ('recommended_action', models.TextField()),
                ('legislation_ref', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'rule_id'],
            },
        ),
        migrations.CreateModel(
            name='ClientAssociate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(help_text='e.g. "Director", "Related Entity", "Shareholder"', max_length=50)),
                ('abn', models.CharField(blank=True, max_length=11, verbose_name='ABN')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='core.client')),
                ('related_entity', models.ForeignKey(blank=True, help_text='Link to an entity in the system if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_as', to='core.entity')),
            ],
            options={
                'ordering': ['client', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskReferenceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('applicable_fy', models.CharField(blank=True, help_text='Financial year this applies to, e.g. "FY2025" or blank for all', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reference_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Reference Data',
                'verbose_name_plural': 'Risk Reference Data',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(help_text='Groups flags from the same analysis run')),
                ('rule_id', models.CharField(max_length=20)),
                ('tier', models.IntegerField()),
                ('severity', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('affected_accounts', models.JSONField(default=list)),
                ('calculated_values', models.JSONField(default=dict)),
                ('recommended_action', models.TextField()),
                ('legislation_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto-Resolved')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='core.financialyear')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risk_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['financial_year', 'status'], name='core_riskfl_financi_4e0a4e_idx'), models.Index(fields=['financial_year', 'severity'], name='core_riskfl_financi_d45013_idx'), models.Index(fields=['run_id'], name='core_riskfl_run_id_7fc697_idx')],
            },
        ),
    ]
