# Generated by Django 5.2.11 on 2026-02-18 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_risk_models_and_client_associate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('sole_trader', 'Sole Trader'), ('smsf', 'SMSF')], help_text='Which entity type this account belongs to', max_length=20)),
                ('account_code', models.CharField(help_text='Account code, e.g. "0500", "1510", "2000.01"', max_length=20)),
                ('account_name', models.CharField(help_text='Account name, e.g. "Sales", "Accountancy"', max_length=255)),
                ('classification', models.CharField(blank=True, default='', help_text='Tax classification, e.g. "Other sales revenue", "Trading income"', max_length=255)),
                ('section', models.CharField(choices=[('suspense', 'Suspense'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of Sales'), ('expenses', 'Expenses'), ('assets', 'Assets'), ('liabilities', 'Liabilities'), ('equity', 'Equity'), ('capital_accounts', 'Capital Accounts'), ('pl_appropriation', 'P&L Appropriation')], help_text='Which section of the financial statements this belongs to', max_length=30)),
                ('tax_code', models.CharField(blank=True, default='', help_text='Default tax code: GST, ADS, ITS, FRE, CAP, INP, etc.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order within the section')),
                ('maps_to', models.ForeignKey(blank=True, help_text='Which financial statement line item this rolls up to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_accounts', to='core.accountmapping')),
            ],
            options={
                'ordering': ['entity_type', 'section', 'account_code'],
                'indexes': [models.Index(fields=['entity_type', 'section'], name='core_charto_entity__80fdb3_idx'), models.Index(fields=['entity_type', 'is_active'], name='core_charto_entity__74c2ea_idx')],
                'unique_together': {('entity_type', 'account_code')},
            },
        ),
    ]
