# Generated by Django 5.2.11 on 2026-02-18 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_chart_of_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientassociate',
            options={'ordering': ['client', 'relationship_type', 'name']},
        ),
        migrations.AddField(
            model_name='clientassociate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientassociate',
            name='employer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientassociate',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientassociate',
            name='related_client',
            field=models.ForeignKey(blank=True, help_text='Link to another client in the system if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_from', to='core.client'),
        ),
        migrations.AddField(
            model_name='clientassociate',
            name='tfn_last_three',
            field=models.CharField(blank=True, help_text='Last 3 digits of TFN for identification (never store full TFN)', max_length=3),
        ),
        migrations.AddField(
            model_name='clientassociate',
            name='xpm_contact_uuid',
            field=models.CharField(blank=True, help_text='Xero Practice Manager contact UUID for sync', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientassociate',
            name='relationship_type',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('family_other', 'Other Family Member'), ('director', 'Director'), ('shareholder', 'Shareholder'), ('partner_biz', 'Business Partner'), ('trustee', 'Trustee'), ('beneficiary', 'Beneficiary'), ('related_entity', 'Related Entity'), ('accountant', 'Accountant / Advisor'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='AccountingSoftware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('software_type', models.CharField(choices=[('xero', 'Xero'), ('myob', 'MYOB'), ('quickbooks', 'QuickBooks'), ('sage', 'Sage'), ('reckon', 'Reckon'), ('access_ledger', 'Access Ledger'), ('excel', 'Excel / Spreadsheet'), ('manual', 'Manual / Paper-based'), ('other', 'Other'), ('none', 'None / Not Applicable')], max_length=20)),
                ('software_version', models.CharField(blank=True, help_text='e.g. "Xero Standard", "MYOB AccountRight Plus", "QuickBooks Online"', max_length=100)),
                ('is_cloud', models.BooleanField(default=True, help_text='Whether this is a cloud-based or desktop installation')),
                ('login_email', models.EmailField(blank=True, help_text="Client's login email for this software (for support reference)", max_length=254)),
                ('organisation_name', models.CharField(blank=True, help_text='Organisation name within the software', max_length=255)),
                ('has_advisor_access', models.BooleanField(default=False, help_text='Whether MC&S has advisor/accountant access to this software')),
                ('advisor_login_email', models.EmailField(blank=True, help_text='MC&S advisor login email for this software', max_length=254)),
                ('subscription_level', models.CharField(blank=True, help_text='e.g. "Starter", "Standard", "Premium"', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this is the primary accounting software for this client/entity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_configs', to='core.client')),
                ('entity', models.ForeignKey(blank=True, help_text='Optionally link to a specific entity (if different from client default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_configs', to='core.entity')),
            ],
            options={
                'verbose_name': 'Accounting Software',
                'verbose_name_plural': 'Accounting Software',
                'ordering': ['client', '-is_primary', 'software_type'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. "Annual Review Meeting", "Tax Planning Discussion"', max_length=255)),
                ('meeting_date', models.DateField()),
                ('meeting_type', models.CharField(choices=[('in_person', 'In-Person Meeting'), ('phone', 'Phone Call'), ('video', 'Video Call'), ('email_thread', 'Email Thread'), ('internal', 'Internal Discussion'), ('site_visit', 'Site Visit'), ('other', 'Other')], default='in_person', max_length=20)),
                ('attendees', models.CharField(blank=True, help_text='Comma-separated names, e.g. "Elio Scarton, John Smith, Jane Doe"', max_length=500)),
                ('discussion_points', models.TextField(blank=True, help_text='Key topics discussed during the meeting')),
                ('action_items', models.TextField(blank=True, help_text='Action items and follow-ups arising from the meeting')),
                ('notes', models.TextField(blank=True, help_text='General notes, observations, and context')),
                ('follow_up_date', models.DateField(blank=True, help_text='Date for next follow-up or action', null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin important notes to the top of the list')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g. "tax-planning, smsf, urgent"', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_notes', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, help_text='Optionally link to a specific entity discussed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='core.entity')),
            ],
            options={
                'verbose_name': 'Meeting Note',
                'verbose_name_plural': 'Meeting Notes',
                'ordering': ['-is_pinned', '-meeting_date', '-created_at'],
            },
        ),
    ]
