# Generated by Django 5.2.11 on 2026-02-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_enhance_associates_add_software_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='reporting_framework',
            field=models.CharField(choices=[('GPFR_tier1', 'General Purpose (Tier 1)'), ('GPFR_tier2', 'General Purpose (Tier 2)'), ('SPFR', 'Special Purpose')], default='GPFR_tier1', max_length=20),
        ),
    ]
