# Generated by Django 5.2.11 on 2026-02-18 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_default_reporting_framework_gpfr_tier1'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='Description of stock item, e.g. "Raw Materials", "Finished Goods"', max_length=255)),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, help_text='Opening stock value ($)', max_digits=15)),
                ('closing_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_value', models.DecimalField(decimal_places=2, default=0, help_text='Closing stock value ($)', max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('pushed_to_tb', models.BooleanField(default=False, help_text='Whether this stock item has been pushed to the trial balance')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.financialyear')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'ordering': ['display_order', 'item_name'],
            },
        ),
    ]
