# Generated by Django 5.2.11 on 2026-02-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived clients are hidden from the default list but data is preserved.'),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone for this entity', max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived entities are hidden from the default list but data is preserved.'),
        ),
        migrations.AddField(
            model_name='entity',
            name='xpm_client_id',
            field=models.CharField(blank=True, help_text='Xero Practice Manager reference', max_length=100, verbose_name='XPM Client ID'),
        ),
    ]
