# Generated by Django 5.2.11 on 2026-02-19 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_is_archived_entity_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientassociate',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity this associate is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='core.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='assigned_accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='accountingsoftware',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_configs', to='core.client'),
        ),
        migrations.AlterField(
            model_name='accountingsoftware',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity this software is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_configs', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='clientassociate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to='core.client'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Legacy client link (optional). Entities are now top-level objects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='core.client'),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='core.client'),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity this meeting note is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to='core.entity'),
        ),
    ]
