# Generated by Django 5.2.11 on 2026-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clientassociate_entity_entity_assigned_accountant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Street address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Street address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, default='Australia', max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='entity',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='entity',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='tfn',
            field=models.CharField(blank=True, help_text='Tax File Number', max_length=20, verbose_name='TFN'),
        ),
    ]
