# Generated by Django 5.2.11 on 2026-02-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_entity_address_line_1_entity_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalanceline',
            name='tax_type',
            field=models.CharField(blank=True, default='', help_text='Tax type for GST/BAS reporting (e.g., GST on Income, GST on Expenses, GST Free)', max_length=30),
        ),
    ]
