# Generated by Django 5.2.11 on 2026-02-20 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_tax_type_to_trial_balance_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Bank name (e.g. CBA, Westpac, ANZ)', max_length=100)),
                ('bsb', models.CharField(blank=True, default='', help_text='Bank-State-Branch number (e.g. 063-123)', max_length=20, verbose_name='BSB')),
                ('account_number', models.CharField(blank=True, default='', help_text='Account number', max_length=50)),
                ('account_name', models.CharField(blank=True, default='', help_text='Account name as shown on statement', max_length=255)),
                ('nickname', models.CharField(blank=True, default='', help_text="User-friendly nickname (e.g. 'Main Business Account')", max_length=100)),
                ('account_type', models.CharField(choices=[('cheque', 'Cheque Account'), ('savings', 'Savings Account'), ('credit_card', 'Credit Card'), ('loan', 'Loan Account'), ('term_deposit', 'Term Deposit'), ('other', 'Other')], default='cheque', max_length=20)),
                ('tb_account_code', models.CharField(blank=True, default='', help_text='Linked trial balance account code (e.g. 1-1100)', max_length=20)),
                ('tb_account_name', models.CharField(blank=True, default='', help_text='Linked trial balance account name', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='The entity this bank account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.entity')),
            ],
            options={
                'ordering': ['bank_name', 'account_number'],
                'unique_together': {('entity', 'bsb', 'account_number')},
            },
        ),
    ]
