# Generated by Django 5.2.11 on 2026-02-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityofficer',
            name='is_chairperson',
            field=models.BooleanField(default=False, help_text='Whether this person is the chairperson (used in distribution minutes)'),
        ),
    ]
