# Generated by Django 5.2.11 on 2026-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_is_chairperson_to_officer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityofficer',
            options={'ordering': ['entity', 'display_order', 'full_name'], 'verbose_name': 'Director / Trustee / Beneficiary', 'verbose_name_plural': 'Directors / Trustees / Beneficiaries'},
        ),
        migrations.AddField(
            model_name='entityofficer',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text="Multiple roles for this person, e.g. ['trustee', 'beneficiary']"),
        ),
        migrations.AlterField(
            model_name='entityofficer',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('partner', 'Partner'), ('trustee', 'Trustee'), ('beneficiary', 'Beneficiary'), ('secretary', 'Secretary'), ('public_officer', 'Public Officer'), ('sole_trader', 'Sole Trader / Proprietor'), ('chairperson', 'Chairperson')], max_length=20),
        ),
    ]
