# Generated by Django 5.2.11 on 2026-02-21 08:47

import config.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_roles_jsonfield_and_chairperson_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("import", "Data Import"),
                    ("adjustment", "Adjustment Created"),
                    ("generate", "Document Generated"),
                    ("status_change", "Status Changed"),
                    ("mapping_change", "Mapping Changed"),
                    ("user_change", "User Modified"),
                    ("template_change", "Template Modified"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="contact_phone",
            field=config.encryption.EncryptedCharField(
                blank=True,
                help_text="Primary contact phone for this entity",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="tfn",
            field=config.encryption.EncryptedCharField(
                blank=True,
                help_text="Tax File Number (encrypted at rest)",
                max_length=255,
                verbose_name="TFN",
            ),
        ),
    ]
