# Generated by Django 5.2.11 on 2026-02-22 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_auditlog_action_alter_entity_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='change_summary',
            field=models.TextField(blank=True, default='', help_text='Summary of what changed from the previous version'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='document_type',
            field=models.CharField(choices=[('financial_statements', 'Financial Statements'), ('distribution_minutes', 'Distribution Minutes'), ('beneficiary_statement', 'Beneficiary Statement'), ('partner_statement', 'Partner Statement'), ('workpaper_notes', 'Working Paper Notes'), ('other', 'Other')], default='financial_statements', max_length=30),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked when financial year is finalised - becomes the definitive version'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Points to the newer version that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.generateddocument'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number (auto-incremented on regeneration)'),
        ),
        migrations.AddField(
            model_name='trialbalanceline',
            name='comparatives_locked',
            field=models.BooleanField(default=False, help_text='Locked when the current year is finalised'),
        ),
        migrations.AddField(
            model_name='trialbalanceline',
            name='prior_balance_override',
            field=models.BooleanField(default=False, help_text='True if prior year balance was manually overridden (Year 1 onboarding)'),
        ),
        migrations.AddField(
            model_name='trialbalanceline',
            name='prior_closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prior year closing balance (auto-populated or manually overridden)', max_digits=15),
        ),
        migrations.AddField(
            model_name='trialbalanceline',
            name='prior_mapped_line_item',
            field=models.ForeignKey(blank=True, help_text='Prior year mapping (for reclassification tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prior_trial_balance_lines', to='core.accountmapping'),
        ),
        migrations.AddField(
            model_name='trialbalanceline',
            name='reclassified',
            field=models.BooleanField(default=False, help_text='True if account mapping changed between years (triggers note disclosure)'),
        ),
        migrations.AlterField(
            model_name='clientassociate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_associates', to='core.client'),
        ),
        migrations.CreateModel(
            name='EntityImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('validated', 'Validated'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='Maps spreadsheet columns to StatementHub fields')),
                ('total_rows', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors: [{row, field, message}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, help_text='Net profit available for distribution', max_digits=15)),
                ('total_salary_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_interest_on_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('residual_profit', models.DecimalField(decimal_places=2, default=0, help_text='Profit remaining after salary allowances and interest on capital', max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_allocation', to='core.financialyear')),
            ],
            options={
                'verbose_name': 'Partnership Allocation',
            },
        ),
        migrations.CreateModel(
            name='TrustDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accounting_profit', models.DecimalField(decimal_places=2, default=0, help_text='Accounting profit from the income statement', max_digits=15)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, help_text='Taxable income after tax adjustments', max_digits=15)),
                ('distributable_income', models.DecimalField(decimal_places=2, default=0, help_text='Total distributable income for the year', max_digits=15)),
                ('capital_gains', models.DecimalField(decimal_places=2, default=0, help_text='Capital gains component', max_digits=15)),
                ('franked_dividends', models.DecimalField(decimal_places=2, default=0, help_text='Franked dividends component', max_digits=15)),
                ('foreign_income', models.DecimalField(decimal_places=2, default=0, help_text='Foreign income component', max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, help_text='Other income component', max_digits=15)),
                ('corpus', models.DecimalField(decimal_places=2, default=0, help_text='Trust corpus (capital) amount', max_digits=15)),
                ('reconciliation_adjustments', models.JSONField(blank=True, default=list, help_text='List of adjustment items: [{label, amount}]')),
                ('is_fully_allocated', models.BooleanField(default=False, help_text='True when 100% of distributable income is allocated to beneficiaries')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_distribution', to='core.financialyear')),
            ],
            options={
                'verbose_name': 'Trust Distribution',
                'verbose_name_plural': 'Trust Distributions',
            },
        ),
        migrations.CreateModel(
            name='PartnerCapitalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('drawings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, help_text='Populated from PartnerShare.total_share', max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_capital_accounts', to='core.financialyear')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_accounts', to='core.entityofficer')),
            ],
            options={
                'ordering': ['partner__full_name'],
                'unique_together': {('financial_year', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='PartnerShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_on_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('residual_share_pct', models.DecimalField(decimal_places=4, default=0, help_text='Percentage share of residual profit', max_digits=7)),
                ('residual_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_share', models.DecimalField(decimal_places=2, default=0, help_text='Total profit share for this partner', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_shares', to='core.entityofficer')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_shares', to='core.partnershipallocation')),
            ],
            options={
                'ordering': ['partner__full_name'],
                'unique_together': {('allocation', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, help_text='Percentage of distributable income (0-100)', max_digits=7)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed dollar amount (alternative to percentage)', max_digits=15, null=True)),
                ('allocated_capital_gains', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_franked_dividends', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_foreign_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allocated_other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_distribution', models.DecimalField(decimal_places=2, default=0, help_text='Total distribution to this beneficiary', max_digits=15)),
                ('section_100a_flag', models.BooleanField(default=False, help_text='Flagged for Section 100A review (reimbursement arrangement risk)')),
                ('section_100a_notes', models.TextField(blank=True, default='', help_text='Notes regarding Section 100A assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(help_text='The beneficiary receiving this allocation', on_delete=django.db.models.deletion.CASCADE, related_name='trust_allocations', to='core.entityofficer')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.trustdistribution')),
            ],
            options={
                'ordering': ['beneficiary__full_name'],
                'unique_together': {('distribution', 'beneficiary')},
            },
        ),
        migrations.CreateModel(
            name='WorkpaperNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(help_text='Trial balance account code this note is attached to', max_length=20)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('note_type', models.CharField(choices=[('preparer', 'Preparer Note'), ('reviewer', 'Reviewer Note')], default='preparer', max_length=10)),
                ('status', models.CharField(choices=[('blank', 'Blank'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='blank', max_length=15)),
                ('content', models.TextField(blank=True, default='', help_text='Working paper note content')),
                ('is_carried_forward', models.BooleanField(default=False, help_text='True if this note was carried forward from the prior year')),
                ('source_year_label', models.CharField(blank=True, default='', help_text='Year label of the source note if carried forward', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workpaper_notes', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpaper_notes', to='core.financialyear')),
            ],
            options={
                'ordering': ['account_code', 'note_type'],
                'indexes': [models.Index(fields=['financial_year', 'account_code'], name='core_workpa_financi_9f1930_idx')],
            },
        ),
    ]
