# Generated by Django 5.2.11 on 2026-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workpaper_note_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskflag',
            name='ai_data_hash',
            field=models.CharField(blank=True, default='', help_text='MD5 hash of flag data at time of AI analysis (cache key)', max_length=32),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='ai_explanation',
            field=models.TextField(blank=True, default='', help_text='AI-generated plain-English explanation of this risk'),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='ai_suggested_action',
            field=models.TextField(blank=True, default='', help_text='AI-generated recommended action for the accountant'),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='ato_interest_reasoning',
            field=models.TextField(blank=True, default='', help_text='AI reasoning for the ATO interest score'),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='ato_interest_score',
            field=models.IntegerField(blank=True, help_text='AI-scored likelihood of ATO interest (1-10)', null=True),
        ),
    ]
