# Generated by Django 5.2.11 on 2026-02-22 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_riskflag_ai_data_hash_riskflag_ai_explanation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='primary_accountant',
            field=models.ForeignKey(blank=True, help_text="The accountant primarily responsible for this entity's work.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text="The senior accountant or partner who reviews this entity's work.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='ai_feedback',
            field=models.CharField(blank=True, default='', help_text='User feedback on AI analysis: correct, partially_correct, incorrect, irrelevant', max_length=30),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='ai_feedback_notes',
            field=models.TextField(blank=True, default='', help_text='User notes explaining the feedback/correction'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('login', 'User Login'), ('logout', 'User Logout'), ('import', 'Data Import'), ('adjustment', 'Adjustment Created'), ('generate', 'Document Generated'), ('status_change', 'Status Changed'), ('mapping_change', 'Mapping Changed'), ('user_change', 'User Modified'), ('template_change', 'Template Modified'), ('ai_feedback', 'AI Feedback')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='assigned_accountant',
            field=models.ForeignKey(blank=True, help_text='Legacy field — use primary_accountant instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
