# Generated by Django 5.2.11 on 2026-02-21 08:47

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_totp_confirmed_user_totp_secret_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=config.encryption.EncryptedCharField(
                blank=True, default="", max_length=255
            ),
        ),
    ]
