# Generated by Django 5.2.11 on 2026-02-17 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('new_statement', 'New statement received'), ('review_completed', 'Review completed'), ('ai_improved', 'AI accuracy improved'), ('review_started', 'Review started')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Review activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airtable_record_id', models.CharField(blank=True, help_text='Airtable record ID for syncing', max_length=50, null=True, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(blank=True, default='', max_length=500)),
                ('submitted_by', models.CharField(blank=True, default='', max_length=255)),
                ('total_transactions', models.IntegerField(default=0)),
                ('auto_coded_count', models.IntegerField(default=0)),
                ('flagged_count', models.IntegerField(default=0)),
                ('confirmed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('awaiting_review', 'Awaiting Review'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='awaiting_review', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airtable_record_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ai_suggested_code', models.CharField(blank=True, default='', max_length=20)),
                ('ai_suggested_name', models.CharField(blank=True, default='', max_length=255)),
                ('ai_confidence', models.IntegerField(default=0, help_text='1-5 scale')),
                ('confirmed_code', models.CharField(blank=True, default='', max_length=20)),
                ('confirmed_name', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_tax_type', models.CharField(blank=True, choices=[('', '— Select —'), ('GST on Income', 'GST on Income'), ('GST on Expenses', 'GST on Expenses'), ('GST Free Income', 'GST Free Income'), ('GST Free Expenses', 'GST Free Expenses'), ('BAS Excluded', 'BAS Excluded')], default='', max_length=30)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='review.reviewjob')),
            ],
            options={
                'ordering': ['date', 'description'],
            },
        ),
    ]
