# Generated by Django 5.2.11 on 2026-02-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='ai_suggested_tax_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewjob',
            name='airtable_record_id',
            field=models.CharField(blank=True, help_text='Airtable record ID for syncing (optional)', max_length=50, null=True),
        ),
    ]
