# Generated by Django 5.2.11 on 2026-02-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_pendingtransaction_ai_suggested_tax_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransaction',
            name='date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
