# Generated by Django 5.2.11 on 2026-02-17 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_entity_is_gst_registered'),
        ('review', '0003_alter_pendingtransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='ai_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='confirmed_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Accountant-confirmed GST amount (if different from AI calc)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='from_learning',
            field=models.BooleanField(default=False, help_text='True if this classification came from the learning database'),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST component (amount/11 for GST items, 0 for GST-free)', max_digits=12),
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net amount excluding GST', max_digits=12),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='bsb',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='Linked entity for GST registration lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_jobs', to='core.entity'),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='is_gst_registered',
            field=models.BooleanField(default=True, help_text="Whether GST applies to this job's transactions"),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='period_end',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='period_start',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewjob',
            name='source',
            field=models.CharField(choices=[('email', 'Email Ingestion'), ('upload', 'Manual Upload'), ('airtable', 'Airtable Sync')], default='airtable', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Gross amount from bank statement (inc GST if applicable)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='confirmed_tax_type',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('GST on Income', 'GST on Income'), ('GST on Expenses', 'GST on Expenses'), ('GST Free Income', 'GST Free Income'), ('GST Free Expenses', 'GST Free Expenses'), ('Input Taxed', 'Input Taxed'), ('BAS Excluded', 'BAS Excluded'), ('N-T', 'Not Reportable')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewactivity',
            name='activity_type',
            field=models.CharField(choices=[('new_statement', 'New statement received'), ('review_completed', 'Review completed'), ('ai_improved', 'AI accuracy improved'), ('review_started', 'Review started'), ('email_received', 'Email received'), ('email_processed', 'Email processed')], max_length=30),
        ),
        migrations.CreateModel(
            name='TransactionPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description_pattern', models.CharField(help_text='Normalised transaction description for matching', max_length=500)),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('tax_type', models.CharField(blank=True, default='', max_length=30)),
                ('usage_count', models.IntegerField(default=1, help_text='Number of times this pattern has been confirmed')),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, help_text='Entity-specific pattern. Null = global pattern.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_patterns', to='core.entity')),
            ],
            options={
                'ordering': ['-usage_count', '-last_used'],
                'unique_together': {('entity', 'description_pattern')},
            },
        ),
    ]
