# Generated by Django 5.2.11 on 2026-02-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_pendingtransaction_ai_reasoning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewactivity',
            name='activity_type',
            field=models.CharField(choices=[('new_statement', 'New statement received'), ('review_completed', 'Review completed'), ('ai_improved', 'AI accuracy improved'), ('review_started', 'Review started')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewjob',
            name='source',
            field=models.CharField(choices=[('upload', 'Manual Upload'), ('airtable', 'Airtable Sync')], default='airtable', max_length=20),
        ),
    ]
