# Generated by Django 5.2.11 on 2026-02-17 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_adjustingjournal_reversal_of_journal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('xero', 'Xero'), ('myob', 'MYOB'), ('quickbooks', 'QuickBooks Online')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, default='', help_text='Xero tenant ID, MYOB company file URI, or QBO realm ID', max_length=255)),
                ('tenant_name', models.CharField(blank=True, default='', help_text='Display name of the connected organisation', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_connections', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_connections', to='core.entity')),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lines_imported', models.IntegerField(default=0)),
                ('lines_unmapped', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('as_at_date', models.DateField(blank=True, help_text='The date the trial balance was pulled as at', null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='integrations.accountingconnection')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imports', to='core.financialyear')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('entity', 'provider'), name='unique_active_connection_per_entity_provider'),
        ),
    ]
