# Generated by Django 5.2.11 on 2026-02-18 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPMConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, default='', max_length=255)),
                ('tenant_name', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('clients_synced', models.IntegerField(default=0)),
                ('contacts_synced', models.IntegerField(default=0)),
                ('relationships_synced', models.IntegerField(default=0)),
                ('notes_synced', models.IntegerField(default=0)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xpm_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='XPMSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('clients', 'Clients Only'), ('contacts', 'Contacts Only'), ('notes', 'Notes Only')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial (with errors)')], default='running', max_length=20)),
                ('clients_created', models.IntegerField(default=0)),
                ('clients_updated', models.IntegerField(default=0)),
                ('entities_created', models.IntegerField(default=0)),
                ('contacts_synced', models.IntegerField(default=0)),
                ('relationships_synced', models.IntegerField(default=0)),
                ('notes_synced', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.xpmconnection')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
