# Generated by Django 5.2.11 on 2026-02-21 08:47

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_myobglobalconnection_qbglobalconnection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingconnection",
            name="access_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="accountingconnection",
            name="refresh_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="myobcompanyfile",
            name="cf_password",
            field=config.encryption.EncryptedCharField(
                blank=True,
                default="",
                help_text="Company file password (encrypted at rest)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="myobcompanyfile",
            name="cf_username",
            field=config.encryption.EncryptedCharField(
                blank=True,
                default="Administrator",
                help_text="Company file username",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="myobglobalconnection",
            name="access_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="myobglobalconnection",
            name="refresh_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="qbglobalconnection",
            name="access_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="qbglobalconnection",
            name="refresh_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="qbtenant",
            name="access_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="qbtenant",
            name="refresh_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="xeroglobalconnection",
            name="access_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="xeroglobalconnection",
            name="refresh_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="xpmconnection",
            name="access_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="xpmconnection",
            name="refresh_token",
            field=config.encryption.EncryptedTextField(blank=True, default=""),
        ),
    ]
